Twilio SMS script
Python-World/Python_and_the_Web pull request #106
Opened 2020-10-01 14:25 UTC by Ajay-Raj-S

# Description

Sending SMS to people by creating a free Twilio account.

Fixes #36 

## Type of change

- **`[X]`** New feature (non-breaking change which adds functionality)

# Checklist:

- **`[X]`** I have named my files and folder, according to this project's guidelines.
- **`[X]`** My code follows the style guidelines of this project.
- **`[X]`** My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- **`[X]`** I have commented on my code, particularly in hard-to-understand areas.
- **`[X]`** I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- **`[X]`** I have included a requirements.txt file (if external libraries are required.)
- **`[X]`** My changes do not produce any warnings.
- **`[X]`** I have added a working sample/screenshot of the script.

2020-10-02 02:56 UTC, AdityaJ7 commented on Scripts/twilio_sms/twilio_sms.py
> +
Add a function for this piece of code

2020-10-02 02:57 UTC, AdityaJ7 requested changes
Make functions for the later part of the code and you are good to go

2020-10-02 11:07 UTC, Ajay-Raj-S commented
Hello @AdityaJ7 I will update it soon.

2020-10-02 11:33 UTC, Ajay-Raj-S commented
Hello @AdityaJ7 , How to fix the check on DeepSource: error? Little help please

2020-10-02 14:31 UTC, AdityaJ7 commented
> Hello @AdityaJ7 , How to fix the check on DeepSource: error? Little help please

It will be fixed automatically don't worry about it

2020-10-02 14:50 UTC, tusharnankani approved these changes

2020-10-03 04:16 UTC, Ajay-Raj-S commented
> > Hello @AdityaJ7 , How to fix the check on DeepSource: error? Little help please
> 
> It will be fixed automatically don't worry about it

Thank you, waiting for your approval.

2020-10-04 10:06 UTC, AdityaJ7 approved these changes

2020-10-04 10:07 UTC, AdityaJ7 commented
@all-contributors please add @Ajay-Raj-S for code

2020-10-04 10:07 UTC, merged

2020-10-05 04:31 UTC, Ajay-Raj-S commented
Thank you @AdityaJ7.