Scraping Data from Flipkart Website using Python
Python-World/Python_and_the_Web pull request #111
Opened 2020-10-01 15:54 UTC by ShivamKumarSah

In this program, I have scraped the mobile phone prices, ratings, and model name from Flipkart, which is one of the popular e-commerce websites.

# Description

A short summary of what is included in your Pull Request.

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [ ] I have named my files and folder, according to this project's guidelines.
- [ ] My code follows the style guidelines of this project.
- [ ] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

2020-10-01 16:06 UTC, chavarera requested changes
Please add proper Readme.md

2020-10-01 16:06 UTC, chavarera commented on Web_scraping_using_python
> +# price = container.find_all("div",{"class": "col col-5-12 _2o7WAb"})
do not put any commented code please remove it
```suggestion
# price = container.find_all("div",{"class": "col col-5-12 _2o7WAb"})  
```

2020-10-01 16:06 UTC, chavarera commented on Web_scraping_using_python
> +page_soup = soup(page_html, features="html.parser")
create a function to get beautiful soup object

2020-10-02 04:00 UTC, AdityaJ7 requested changes
Make the changes as requested by chavarera

2020-10-03 18:28 UTC, tusharnankani commented
Are you working on it? @ShivamKumarSah

2020-10-14 14:37 UTC, chavarera requested changes
@ShivamKumarSah are you working on it?

2020-10-26 11:58 UTC, closed without merging