Add Python Script for Realtime-Face-Detection
Python-World/Python_and_the_Web pull request #194
Opened 2020-10-02 14:41 UTC by pksgmv

# Description

Python Script for a Realtime Face Detection App using Python-OpenCV.

Fixes #31 

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [X] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

2020-10-05 03:08 UTC, AdityaJ7 commented
hey @pksgmv can you remove the xml file and just mention a link from which it can be downloaded?

2020-10-05 03:09 UTC, AdityaJ7 requested changes
hey @pksgmv can you remove the xml file and just mention a link from which it can be downloaded?
also adjust your readme file and add a requirments.txt file

2020-10-05 04:00 UTC, pksgmv commented
> hey @pksgmv can you remove the xml file and just mention a link from which it can be downloaded?
> also adjust your readme file and add a requirments.txt file
> 

Okay @AdityaJ7 I'll make the above changes and then make a PR...

2020-10-26 14:34 UTC, tusharnankani reviewed
> > hey @pksgmv can you remove the xml file and just mention a link from which it can be downloaded?
> 
> Okay @AdityaJ7 I'll make the above changes and then make a PR...

The `.xml` file is still there, please remove it.

 > also adjust your readme file and add a requirments.txt file

Also, you can refer to the [README Template,](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)

2020-10-26 14:35 UTC, tusharnankani commented on Scripts/Miscellaneous/Realtime_Face_Detection/face_detector.py
> +        break
Fix the DeepSource error.

2020-10-26 14:45 UTC, pksgmv commented
@tusharnankani Okay. I'll make another PR looking into the errors...

2020-10-27 04:01 UTC, tusharnankani commented
> @tusharnankani Okay. I'll make another PR looking into the errors...

You don't need to create another PR, you can push the changes directly to the respective branch you checked out to, and the changes will be made.

2020-10-31 06:28 UTC, chavarera approved these changes

2020-11-07 12:30 UTC, closed without merging