Added hacktoberfest events scrapper
Python-World/Python_and_the_Web pull request #23
Opened 2020-09-26 06:28 UTC by AdityaJ7

# Description

Script to scrape the events related to hacktoberfest 2020.

Fixes #22

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

2020-09-26 10:51 UTC, tusharnankani approved these changes
The script works well! 👍🏻

2020-09-26 19:49 UTC, chavarera requested changes

2020-09-26 19:49 UTC, chavarera commented on Scripts/Web_Scrappers/Hacktoberfest_Events/hacktoberfest_events.py
> +    df1.to_csv('hacktoberfest_events.csv')
write functions to perform single task

create a separate function to csv file

2020-09-27 06:39 UTC, chavarera approved these changes
good work @AdityaJ7 no new changes required

----------------------------
Make a common utility file to handle network request or handling specific operation so we can use that same utility functions in upcoming coding projects.

2020-09-27 06:47 UTC, AdityaJ7 commented
> good work @AdityaJ7 no new changes required
> 
> Make a common utility file to handle network request or handling specific operation so we can use that same utility functions in upcoming coding projects.

Ok!

2020-09-27 06:47 UTC, merged