MLB_Stats Scrapper
Python-World/Python_and_the_Web pull request #24
Opened 2020-09-29 15:21 UTC by Tomyzon1728

# Description

A short summary of what is included in your Pull Request.

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [ ] I have named my files and folder, according to this project's guidelines.
- [ ] My code follows the style guidelines of this project.
- [ ] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

2020-09-29 15:24 UTC, Tomyzon1728 commented
@AdityaJ7 and @chavarera , I've followed due process and my code works perfectly

2020-09-30 03:52 UTC, AdityaJ7 requested changes
Please make a script which takes input from the user about the player whose stat they want to scarpe.
Don't use jupyter notebook.

Jupyter Notebook is good for analysis purpose, but here we want to make a dynamic script which can be used by others directly from the command line without making changes in the code.

Please read issue statement carefully.

Thanks

2020-09-30 15:00 UTC, Tomyzon1728 commented
Ok will make changes

2020-09-30 15:59 UTC, chavarera requested changes
Don't Add multiple out put files

Make a script instead of writing code in notebook

2020-09-30 19:15 UTC, Tomyzon1728 commented
Ok will do that before tomorrow

2020-09-30 20:52 UTC, Tomyzon1728 commented
@AdityaJ7 I've changed the jupyter notebook to a python script. Also, the issue was to convert MLB stats to a CSV file .
@chavarera made the required changes as well .

2020-10-01 03:17 UTC, AdityaJ7 requested changes
Please add a requirements.txt file and add a screenshot of calling the script from the terminal  and remove the old screenshot that you provided

Also please comment your code in necessary areas and please divide your code into functions!

2020-10-01 03:20 UTC, AdityaJ7 commented
> @AdityaJ7 I've changed the jupyter notebook to a python script. Also, the issue was to convert MLB stats to a CSV file .
> @chavarera made the required changes as well .

@Tomyzon1728  Read the issue again carefully , it says the user of the script must enter the name of the player whose stat they want to scrape!!!!

You have hardcoded one player only

2020-10-01 03:40 UTC, chavarera requested changes
Add different functions to perform specific tasks

2020-10-01 03:40 UTC, chavarera commented on Scripts/Web_Scrappers/MLB_Scrapper/MLB.py
> +page = requests.get (url)
Follow DRY(Don't Repeat Yourself) principal

write a separate function which perform following task(Single function)

```
Accept URL,
Create Request
Get Page Source
Convert Into Soup Object
Return soup object
```

2020-10-01 08:20 UTC, Tomyzon1728 commented
Ok will make necessary edit
Thanks guys

2020-10-03 06:18 UTC, chavarera requested changes
write a separate function which perform following task(Single function)

2020-10-14 14:36 UTC, chavarera commented
@Tomyzon1728 are you working on it?

2020-10-18 15:34 UTC, AdityaJ7 commented
Will close this PR after 2 days @Tomyzon1728

2020-10-26 11:56 UTC, closed without merging