Added Angle Arrow Detector Project.
Python-World/Python_and_the_Web pull request #273
Opened 2020-10-03 14:58 UTC by VyomGarg47

# Description

Added Arrow detector project which detects any arrow, along with its directions, from a live camera feed.
Fixes #263 
Replace `issue_no` in the above line, with the issue related to this PR.
## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

2020-10-06 19:17 UTC, tusharnankani requested changes
- Please follow this [README TEMPLATE.](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)

2020-10-06 19:17 UTC, tusharnankani commented on Scripts/Miscellaneous/Arrow_Angle_detector/Arrow.py
> +						#distance2 = (x1 - x3)*(x1 - x3) + (y1 - y3)*(y1 - y3)
Remove unnecessary commented out code lines, add comments instead for better understanding,

2020-10-06 19:17 UTC, tusharnankani commented on Scripts/Miscellaneous/Arrow_Angle_detector/Arrow.py
> +
Please remove this.

2020-10-07 19:01 UTC, VyomGarg47 commented
I have made the necessary changes. Kindly review.

2020-10-09 11:25 UTC, AdityaJ7 requested changes
Break your code into functions, where each function performs a specific task, in order to improve the readability of the code.

2020-10-19 14:23 UTC, tusharnankani commented
> Break your code into functions, where each function performs a specific task, in order to improve the readability of the code.

Are you working on it? @VyomGarg47

2020-10-20 05:51 UTC, VyomGarg47 commented
@tusharnankani I'm extremely sorry for the delay. Kindly review again.

2020-10-20 06:02 UTC, tusharnankani approved these changes
Looks good to me! 👍🏻

2020-10-21 05:27 UTC, AdityaJ7 approved these changes

2020-10-21 05:27 UTC, AdityaJ7 commented
@allcotributors please add @VyomGarg47 for code

2020-10-21 05:27 UTC, merged

2020-10-21 05:30 UTC, AdityaJ7 commented
@allcontributors please add @VyomGarg47 for code