File Organizer
Python-World/Python_and_the_Web pull request #281
Opened 2020-10-03 17:43 UTC by officialpm

# Description

Auto organizing files into images, music, videos executables, documents folders

Fixes #241 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

2020-10-04 11:47 UTC, AdityaJ7 commented
@officialpm can you add a working screenshot of the script

2020-10-04 11:50 UTC, AdityaJ7 requested changes
@officialpm can you add a working screenshot of the script

Also mention on which operating system have you tested it

2020-10-04 11:51 UTC, officialpm commented
> @officialpm can you add a working screenshot of the script

Yes will add it!

2020-10-04 20:34 UTC, Apex-code approved these changes

2020-10-05 02:51 UTC, AdityaJ7 approved these changes

2020-10-05 02:52 UTC, merged