feat: Added a Script which changes Desktop Wallpaper (Windows). Issue…
Python-World/Python_and_the_Web pull request #353
Opened 2020-10-04 15:38 UTC by symtalha14

… #349

Added a new folder Windows_Wallpaper_Changer in Scripts/Miscellaneous. It has got a simple python script which changes the windows desktop wallpaper by prompting the user to select an image.

# Description

A short summary of what is included in your Pull Request.

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [ ] I have named my files and folder, according to this project's guidelines.
- [ ] My code follows the style guidelines of this project.
- [ ] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

2020-10-05 14:24 UTC, tusharnankani requested changes
The script works fine! @symtalha14 👍🏻 

Please add a README.md file in your directory according to [this template](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)!

2020-10-05 14:24 UTC, tusharnankani commented on Scripts/Miscellaneous/Windows_Wallpaper_Changer/background.py
> +
This import is not used anywhere, please remove this!

2020-10-05 16:31 UTC, tusharnankani approved these changes

2020-10-05 16:31 UTC, tusharnankani commented on Scripts/Miscellaneous/Windows_Wallpaper_Changer/background.py
> +
Remove the extra lines.

2020-10-05 16:37 UTC, symtalha14 commented
I hope everything is in place now :)

2020-10-05 18:11 UTC, symtalha14 commented
Could you please consider merging if everything is alright :')

2020-10-05 19:16 UTC, tusharnankani commented
It will automatically get merged, when two or more maintainers/owners approve the changes! 

Thanks to our very own - `mergify` bot. ^_^

2020-10-06 02:54 UTC, AdityaJ7 approved these changes

2020-10-06 02:54 UTC, AdityaJ7 commented
@all-contributors please add @symtalha14 for code

2020-10-06 02:54 UTC, merged