Added 15Puzzle
Python-World/Python_and_the_Web pull request #514
Opened 2020-10-14 10:28 UTC by ADV1K

Game Added. This is what the game looks like:
![demo](https://user-images.githubusercontent.com/35737096/95977089-06339a00-0e36-11eb-9899-11ae48fbfa80.gif)
![score](https://user-images.githubusercontent.com/35737096/95977095-0895f400-0e36-11eb-900e-e19e57151fa4.png)

2020-10-15 03:11 UTC, AdityaJ7 requested changes
Add a README.md file and don't clear the PR Template from next time

2020-10-15 19:31 UTC, tusharnankani requested changes
- Requesting you to follow the Code of Conduct, otherwise, the PRs could be marked invalid/spam.
- Please stick to the PR template.

2020-10-15 19:31 UTC, tusharnankani commented on Scripts/Miscellaneous/15Puzzle/15puzzle.py
> +'''
- Please remove this and create a README file according to the [README TEMPLATE](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md).

2020-10-16 13:19 UTC, ADV1K commented
added a clean PR. so im closing this one

2020-10-16 13:19 UTC, closed without merging