Image Steganography
Python-World/Python_and_the_Web pull request #556
Opened 2020-10-16 17:22 UTC by madhavmehndiratta

# Description
Image Stenography Project

Fixes #200 

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

2020-10-17 11:20 UTC, Apex-code commented
add requirements.txt pls

2020-10-17 11:20 UTC, Apex-code requested changes
Add requirements.txt

2020-10-19 12:30 UTC, Apex-code approved these changes

2020-10-20 10:10 UTC, AdityaJ7 approved these changes

2020-10-20 10:21 UTC, tusharnankani approved these changes

2020-10-20 10:21 UTC, merged