Htmltomd
Python-World/Python_and_the_Web pull request #596
Opened 2020-10-22 12:38 UTC by AdeshChoudhar19

# Description
A simple Python script that uses 'html2text' module to parse a HTML file into markdown file.

Fixes #19 

Replace `issue_no` in the above line, with the issue related to this PR.

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [ ] I have named my files and folder, according to this project's guidelines.
- [ ] My code follows the style guidelines of this project.
- [ ] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [ ] I have included a requirements.txt file (if external libraries are required.)
- [ ] My changes do not produce any warnings.
- [ ] I have added a working sample/screenshot of the script.

2020-10-22 12:41 UTC, AdeshChoudhar19 commented
I have submitted a PR. Please check.

2020-10-23 05:01 UTC, tusharnankani requested changes
Works well! 👍🏻 

Please fix the DeepSource errors.

2020-10-23 06:32 UTC, AdeshChoudhar19 commented
Please check now. And let me know if any changes are required.

2020-10-23 06:36 UTC, tusharnankani approved these changes

2020-10-23 06:48 UTC, AdityaJ7 approved these changes

2020-10-23 06:48 UTC, merged