Merge Images Vertically
Python-World/Python_and_the_Web pull request #597
Opened 2020-10-22 19:12 UTC by jrcamelo

# Description

Adds a script that can merge images inside a subfolder vertically using Pillow.  
It is useful for comics and webtoons.

Fixes #31  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

2020-10-23 05:13 UTC, tusharnankani requested changes
Looks good to me 👍🏻 

- Please comment on your code for better understanding.
- Fix DeepSource errors.

2020-10-25 01:23 UTC, jrcamelo commented
Added comments

2020-10-25 06:53 UTC, AdityaJ7 approved these changes

2020-10-25 10:32 UTC, merged

2020-10-25 10:32 UTC, AdityaJ7 commented
@allcontributors please add @jrcamelo for code