Json2yaml
Python-World/Python_and_the_Web pull request #66
Opened 2020-10-01 05:02 UTC by mendoza

# Description

It converts a json file to a yaml file

Fixes #17

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [X] I have named my files and folder, according to this project's guidelines.
- [X] My code follows the style guidelines of this project.
- [X] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [X] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [X] I have included a requirements.txt file (if external libraries are required.)
- [X] My changes do not produce any warnings.
- [X] I have added a working sample/screenshot of the script.

2020-10-01 05:44 UTC, tusharnankani requested changes

2020-10-01 05:44 UTC, tusharnankani commented on Scripts/Miscellaneous/json2yaml/README.md
> +A simple Python script that uses 'pyyaml' module to conver an input json file into a output yaml file.
Leave a line after every heading

2020-10-01 05:44 UTC, tusharnankani commented on Scripts/Miscellaneous/json2yaml/README.md
> +
use **\```bash** for bash commands and write the commands in the next line, and close **```** it, in the line after that.
```
```bash
<commands>
\```
```

2020-10-01 05:47 UTC, tusharnankani reviewed
Please fix the Readme errors.
And, comment your code for better understanding.

The script works fine. 👍🏻 
Good work.

2020-10-01 09:57 UTC, tusharnankani approved these changes

2020-10-01 10:09 UTC, chavarera requested changes
code is working fine

Suggestions
Add Helper functions instead if writing statement by statement
`A helper function is a function that performs part of the computation of another function. Helper functions are used to make your programs easier to read by giving descriptive names to computations. They also let you reuse computations, just as with functions in general.`

2020-10-01 23:14 UTC, mendoza commented
Is something missing?

2020-10-02 03:02 UTC, AdityaJ7 approved these changes

2020-10-02 03:03 UTC, merged