Add Image-scrapper script
Python-World/Python_and_the_Web pull request #91
Opened 2020-10-01 11:57 UTC by rohitjoshi6

# Description

I want to add a Web-Scrapping script which scrapes images from URL.
Fixes #31

## Type of change

Choosing one or more options from the following as per the nature of your Pull request.
- NOTE: *These boxes can be checked using **`[X]`***

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation Update

# Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Update index.md`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy to understand `README.md`, according to the given [`README_TEMPLATE.`](https://github.com/Python-World/Python_and_the_Web/blob/master/README_TEMPLATE.md)
- [x] I have included a requirements.txt file (if external libraries are required.)
- [x] My changes do not produce any warnings.
- [x] I have added a working sample/screenshot of the script.

2020-10-01 12:04 UTC, AdityaJ7 requested changes
Does this script work only with the hardcoded URL?

If no then add a prompt to ask the user for a URL

Follow the functional programming paradigm and comment your code.

2020-10-01 12:32 UTC, tusharnankani requested changes
- Please fix the README errors.
- Comment your code. 
- Avoid extra lines on code.

2020-10-01 12:32 UTC, tusharnankani commented on Scripts/Web_Scrappers/Image_Scrapper/README.md
> +```python
This will be `bash` instead of python.

2020-10-01 12:32 UTC, tusharnankani commented on Scripts/Web_Scrappers/Image_Scrapper/README.md
> +# Images Scraper
Leave a line after every heading `#`

2020-10-01 12:32 UTC, tusharnankani commented on Scripts/Web_Scrappers/Image_Scrapper/Scraper.py
> +url="https://www.creativeshrimp.com/top-30-artworks-of-beeple.html"
Suggestion: Take URL as an input

2020-10-01 13:07 UTC, rohitjoshi6 commented
I have added the requested feature of taking url as input and fixed the error in README.md file

2020-10-01 17:11 UTC, chavarera requested changes
![Screenshot from 2020-10-01 22-38-08](https://user-images.githubusercontent.com/33047641/94841054-13648800-0437-11eb-9534-99225a7c1085.png)

2020-10-01 17:26 UTC, rohitjoshi6 commented on Scripts/Web_Scrappers/Image_Scrapper/requirements.txt
> +requests
> add appropriate module version using command
> 
> ```
> pip freeze list>requirements.txt
> ```
You mean i should add version of the modules used in the requirements.txt file. right?

2020-10-02 03:20 UTC, AdityaJ7 approved these changes

2020-10-02 11:34 UTC, chavarera submitted a review, later dismissed

2020-10-02 14:58 UTC, rohitjoshi6 commented on Scripts/Web_Scrappers/Image_Scrapper/requirements.txt
> +requests
Its Showing that there's merge conflict. How can i solve this issue?

2020-10-02 15:15 UTC, rohitjoshi6 commented
Can you delete this pull request? i will make a new pull request

2020-10-03 06:11 UTC, chavarera commented
> Can you delete this pull request? i will make a new pull request

@rohitjoshi6 sure please make a new PR

2020-10-03 06:12 UTC, closed without merging